"""added the table course and the table admin

Revision ID: 817664cc53e3
Revises: ada61062c991
Create Date: 2018-12-21 11:18:21.733772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817664cc53e3'
down_revision = 'ada61062c991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('semester', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('teacher', sa.String(length=128), nullable=True),
    sa.Column('session', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'assignment', sa.Column('time_stamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_assignment_time_stamp'), 'assignment', ['time_stamp'], unique=False)
    op.create_foreign_key(None, 'assignment', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'assignment', 'admin', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_constraint(None, 'assignment', type_='foreignkey')
    op.drop_index(op.f('ix_assignment_time_stamp'), table_name='assignment')
    op.drop_column(u'assignment', 'time_stamp')
    op.drop_table('course')
    op.drop_table('admin')
    # ### end Alembic commands ###
