"""assignments table first modified

Revision ID: ada61062c991
Revises: e4b1ee74a131
Create Date: 2018-12-19 11:44:24.095292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada61062c991'
down_revision = 'e4b1ee74a131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment') as batch_op:
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
