"""assignments table

Revision ID: e4b1ee74a131
Revises:
Create Date: 2018-12-19 11:13:31.335724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1ee74a131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('start', sa.TIMESTAMP(), nullable=True),
    sa.Column('end', sa.TIMESTAMP(), nullable=True),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('course_id', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    # ### end Alembic commands ###
